// ============================================================================
// This is auto-generated by gf cli tool only once. Fill this file as you wish.
// ============================================================================

package staffs

import (
	"log"
	"time"

	"github.com/jinzhu/gorm"
)

// Fill with you ideas below.

// Staff 员工表
type Staff struct {
	ID      string `gorm:"primary_key"`
	Name    string
	Age     string
	Address string
}

var db *gorm.DB

// Init 初始化
func Init(link string) {
	var err error
	db, err = gorm.Open("mysql", link+"?charset=utf8&parseTime=True&loc=Local")
	if err != nil {
		log.Fatalln("failed to connect database, ", err)
	}
	db.DB().SetConnMaxLifetime(60 * time.Second)
	// db.LogMode(true)
	db.AutoMigrate(&Staff{})
}

//修改员工信息
func UpdateStaff(ID string, Name string, Age string, Address string) error {
	return db.Table("staffs").Where("id = ?", ID).Updates(Staff{Name: Name, Age: Age, Address: Address}).Error
}
