// ============================================================================
// This is auto-generated by gf cli tool only once. Fill this file as you wish.
// ============================================================================

package custormer_orders

import (
	"log"
	"time"

	"github.com/jinzhu/gorm"
)

// Fill with you ideas below.

// CustormerOrder 客户订单表
type CustormerOrder struct {
	gorm.Model
	Operator        string `gorm:"size:255"`
	Name            string
	Tel             string
	DeliveryAddress string
	DeliveryTime    string
	Amount          float32
	Deposit         float32
	Remarks         string
	State           string `gorm:"default:'未完成'"`
	Freight         float32
}

var db *gorm.DB

// Init 初始化
func Init(link string) {
	var err error
	db, err = gorm.Open("mysql", link+"?charset=utf8&parseTime=True&loc=Local")
	if err != nil {
		log.Fatalln("failed to connect database, ", err)
	}
	db.DB().SetConnMaxLifetime(60 * time.Second)
	// db.LogMode(true)
	db.AutoMigrate(&CustormerOrder{})
}
